# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDJevoNCpHb58boKOXz_2DYud9-ba6zK
"""

import pandas as pd
df = pd.DataFrame ({
                     'Ism Familiya '  :     [    'ABDUXAKIMOV XURSANDBEK ORIBJON O‘G‘LI ' , 'AHMADALIYEV ABBOSXON SAIDJON O‘G‘L ' ,'AZIZIBLOYEV HOJIAKBAR ABDUJALIL O‘G‘LI' ,'DO‘LTABOYEV MUHAMMADJON G‘ANIJON O‘G‘LI', 'MADAMINJONOV BAXTIYORJON SHERZOD O‘G‘LI', 'MAMADALIYEV ZIKRULLO XAYRULLA O‘G‘L', 'MAMATVALIYEV DILSHODBEK XALIMJON O‘G‘L', 'MIRZAHAMIDOV JALOLIDDIN MUZAFFAR O‘G‘LI' ,'NE’MATOVA DILDORAXON XAYRULLOJON QIZI ' ,'NURMUHAMMADOV MUHAMMAD MUXIDDIN O‘G‘LI ' ,'QAMBARALIYEVA NIGORAXON MUXAMMADJON QIZI' ,'QAMBAROV SAMANDARBEK XAYDARALI O‘G‘LI ' ,'RAXMONOV BEKZODJON MUXAMMADMUROT O‘G‘LI ' ,'SHAMSIDINOV SHERZODJON HOJIBOY ZODA', 'SOBIROV MUHAMMADJON IBROHIM O‘G‘LI' ,'SODIQOVA MAXLIYOXON SAFARALI QIZI' ,'SULAYMONOVA MAXLIYOXON VALIJON QIZI ', 'TURG‘UNBOYEV DIYORBEK OYBEK O‘G‘LI' , 'YO‘LDASHEV XUSNIDDIN XASANBOY O‘G‘LI' ,' YUSUBJONOV YAXYOBEK O‘TKIRJON O‘G‘LI ' ,'YUSUBOV TEMUR PO‘LATBOY O‘G‘LI '   ] ,

                     'Yoshi' :     [ '20' , '20' , '20', '20', '20', '20', '20', '20', '20', '20', '20', '20', '20', '20', '20', '20', '20', '20', '20', '20', '20'] ,
                     'Kursi':      [ '2'  , '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2']
})
print(df)

df.to_excel('guruh.xlsx' , index=False, sheet_name='Sheet1')

from google.colab import drive
drive.mount('/content/drive')